# This is a basic workflow to help you get started with Actions

name: Getting issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
